// User Action;
export const DANGNHAPREQUEST = "DANGNHAPREQUEST";
export const DANGNHAPSUCCESS = "DANGNHAPSUCCESS";
export const DANGNHAPFAILED = "DANGNHAPFAILED";
export const CLEARERRORMESSAGE = "CLEARERRORMESSAGE";
export const LOGOUT = "LOGOUT";
export const LAYTHONGTINDATVE = "LAYTHONGTINDATVE";
export const UPDATEUSERINFO = "UPDATEUSERINFO";

// Movie Action
export const GETMOVIELISTREQUEST = "GETMOVIELISTREQUEST";
export const GETMOVIELISTSUCCESS = "GETMOVIELISTSUCCESS";
export const GETMOVIELISTFAILED = "GETMOVIELISTFAILED";
export const GETMOVIEDETAIL = "GETMOVIEDETAIL";
export const GETMOVIEDETAILSUCCESS = "GETMOVIEDETAILSUCCESS";

// Cinema Action
export const LAYHETHONGRAP = "LAYHETHONGRAP";
export const LAYCUMRAP = "LAYCUMRAP";
export const GETINFOSHOWTIMEFROMCINEMA = "GETINFOSHOWTIMEFROMCINEMA";
export const LAYDANHSACHRAPVAPHIMLICHCHIEUMOBILE =
  "LAYDANHSACHRAPVAPHIMLICHCHIEUMOBILE";

// Booking Action
export const LAYDANHSACHPHONGVE = "LAYDANHSACHPHONGVE";
export const LAYDANHSACHPHONGVESUCCESS = "LAYDANHSACHPHONGVESUCCESS";
